server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

# okta:
#   oauth2:
#     issuer: https://dev-34443880.okta.com/oauth2/default
#     audience: api://default
#     client-id: 0oadguywm5zUIfP5g5d7
#     client-secret: TheMEDhDm0l_XANVfjoooAzniPOJ6bU9Ohal5yIBlDz6UBJwY2l-Pu0YxB0IhL-5
#     scopes: openid, profile, email, offline_access
